name: Urfu Testing CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  task1:
    runs-on: ubuntu-22.04
    container:
      image: lifestyle288/urfucpp:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --name main-container
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        cd task1
        cp -R /app/tests/task1 tests
        mkdir build
        cd build
        cmake ..
        make -j4

    - name: Run tests
      run: cd task1/build && ctest
